// Generated by scripts/generate_event_codes.py in ogd-standards from the event standard.
// Do not edit by hand. Regenerate it when the standard changes.

/**
 * Event codes from the OpenGameData event standard, grouped by category and family.
 * Game-specific events can use the X900-X999 codes of any block, or the 9000 block.
 */
export const OGDEvents = Object.freeze({
    Meta: Object.freeze({
        ApplicationLifecycle: Object.freeze({
            /** The application is launched or started. */
            ApplicationLaunched: 1000,
            /** The application is closed or terminated. */
            ApplicationTerminated: 1001,
            /** The application becomes the active foreground application. */
            ApplicationForegrounded: 1002,
            /** The application leaves the foreground. */
            ApplicationBackgrounded: 1003,
        }),
        SessionLifecycle: Object.freeze({
            /** A gameplay session begins. */
            SessionStarted: 1100,
            /** The gameplay session is paused. */
            SessionPaused: 1101,
            /** A paused gameplay session resumes. */
            SessionResumed: 1102,
            /** The gameplay session ends. */
            SessionEnded: 1103,
            /** The gameplay session is reset. */
            SessionReset: 1104,
        }),
        MenuApplicationNavigation: Object.freeze({
            /** The player opens the main application menu. */
            OpenMainMenu: 1200,
            /** The player closes the main application menu. */
            CloseMainMenu: 1201,
            /** The player moves between application-level menu screens without selecting an option. */
            NavigateMenuScreen: 1202,
            /** The player returns to the previous menu screen. */
            ReturnToPreviousMenu: 1203,
            /** The player selects an application-level menu option. */
            SelectMenuOption: 1204,
        }),
        SettingsConfiguration: Object.freeze({
            /** The player opens the settings screen. */
            OpenSettings: 1300,
            /** The player changes a setting value. */
            ChangeSetting: 1301,
            /** Settings are reset to defaults. */
            ResetSettings: 1302,
            /** The settings screen is closed. */
            CloseSettings: 1303,
        }),
        ProfileIdentity: Object.freeze({
            /** A player profile is selected. */
            SelectProfile: 1400,
            /** A player logs in. */
            Login: 1401,
            /** A player logs out. */
            Logout: 1402,
            /** A new player profile is created. */
            CreateProfile: 1403,
            /** A player profile is deleted. */
            DeleteProfile: 1404,
        }),
        LoadingApplicationTransitions: Object.freeze({
            /** Application-level loading begins. */
            StartLoading: 1500,
            /** Application-level loading completes. */
            LoadingComplete: 1501,
            /** A non-gameplay application transition begins. */
            StartApplicationTransition: 1502,
            /** A non-gameplay application transition completes. */
            CompleteApplicationTransition: 1503,
        }),
        Matchmaking: Object.freeze({
            /** The player enters a matchmaking process to be placed into a gameplay session. */
            EnterMatchmaking: 1600,
            /** The player leaves a matchmaking process before being placed into a session. */
            ExitMatchmaking: 1601,
            /** The system identifies a compatible match for the player. */
            MatchmakingMatchFound: 1602,
            /** The player is assigned to a gameplay session or pre-game lobby. */
            MatchmakingAssignment: 1603,
            /** The matchmaking process ends without forming a match. */
            MatchmakingTimeout: 1604,
        }),
    }),
    NarrativeCommunication: Object.freeze({
        Narration: Object.freeze({
            /** Narration sequence becomes available/active. */
            EnterNarration: 2001,
            /** Narration sequence is exited and no longer active. */
            ExitNarration: 2002,
            /** Narration ends before completion due to interruption or quit. */
            AbandonNarration: 2003,
            /** Narration begins advancing/playing. */
            StartNarration: 2010,
            /** Narration reaches its intended end without skipping/abandoning. */
            CompleteNarration: 2011,
            /** Narration display is cleared or no longer available. */
            ClearNarration: 2012,
            /** Narration advances to the next unit (player or system driven). */
            AdvanceNarration: 2013,
            /** Narration is skipped to the end (or past remaining content). */
            SkipNarration: 2014,
        }),
        Dialog: Object.freeze({
            /** Dialog sequence becomes available/active. */
            EnterDialog: 2101,
            /** Dialog sequence is exited and no longer active. */
            ExitDialog: 2102,
            /** Dialog ends before completion due to interruption or quit. */
            AbandonDialog: 2103,
            /** Dialog begins advancing/playing. */
            StartDialog: 2110,
            /** Dialog reaches its intended end (animation/playback finished). */
            CompleteDialog: 2111,
            /** Dialog display is cleared or no longer available. */
            ClearDialog: 2112,
            /** Dialog advances to the next unit (typically player action). */
            AdvanceDialog: 2113,
            /** Dialog is skipped to the end (typically player action). */
            SkipDialog: 2114,
            /** Dialog choice options are displayed to the player. */
            ChoicesDisplayed: 2115,
            /** A dialog choice is selected. */
            ChoiceSelected: 2116,
            /** Player begins a free-text or open response input. */
            FreeResponseInitiated: 2117,
            /** Player submits a dialog response (choice or free response). */
            SubmitResponse: 2118,
        }),
        Tutorialization: Object.freeze({
            /** Tutorial sequence becomes available/active. */
            EnterTutorial: 2201,
            /** Tutorial sequence is exited and no longer active. */
            ExitTutorial: 2202,
            /** Tutorial ends before completion due to interruption or quit. */
            AbandonTutorial: 2203,
            /** Tutorial begins advancing/playing. */
            StartTutorial: 2210,
            /** Tutorial reaches its intended end. */
            CompleteTutorial: 2211,
            /** Tutorial display is cleared or no longer available. */
            ClearTutorial: 2212,
            /** Tutorial advances to the next unit. */
            AdvanceTutorial: 2213,
            /** Tutorial is skipped to the end. */
            SkipTutorial: 2214,
        }),
        PositiveFeedback: Object.freeze({
            /** Positive feedback sequence begins. */
            StartPositiveFeedback: 2310,
            /** Positive feedback sequence completes naturally. */
            CompletePositiveFeedback: 2311,
            /** Positive feedback display is cleared or no longer available. */
            ClearPositiveFeedback: 2312,
            /** Positive feedback advances to the next unit (if multi-part). */
            AdvancePositiveFeedback: 2313,
            /** Positive feedback is skipped to the end. */
            SkipPositiveFeedback: 2314,
        }),
        NegativeFeedback: Object.freeze({
            /** Negative feedback sequence begins. */
            StartNegativeFeedback: 2410,
            /** Negative feedback sequence completes naturally. */
            CompleteNegativeFeedback: 2411,
            /** Negative feedback display is cleared or no longer available. */
            ClearNegativeFeedback: 2412,
            /** Negative feedback advances to the next unit (if multi-part). */
            AdvanceNegativeFeedback: 2413,
            /** Negative feedback is skipped to the end. */
            SkipNegativeFeedback: 2414,
        }),
        Hinting: Object.freeze({
            /** Hint/help sequence begins. */
            StartHint: 2510,
            /** Hint/help sequence completes naturally. */
            CompleteHint: 2511,
            /** Hint/help display is cleared or no longer available. */
            ClearHint: 2512,
            /** Hint/help advances to the next unit. */
            AdvanceHint: 2513,
            /** Hint/help is skipped to the end. */
            SkipHint: 2514,
            /** Player requests a hint/help (player-initiated request). */
            RequestHint: 2515,
        }),
    }),
    Segmentation: Object.freeze({
        GlobalGameplaySegments: Object.freeze({
            /** A global gameplay segment begins. */
            StartGlobalSegment: 3000,
            /** A global gameplay segment ends. */
            EndGlobalSegment: 3001,
            /** Global gameplay segment exits without completion. */
            AbandonGlobalSegment: 3002,
            /** Global gameplay segment resumes/restores. */
            ResumeGlobalSegment: 3003,
        }),
        ExclusiveTopologicalSegments: Object.freeze({
            /** The current exclusive segment begins (e.g., level start). */
            StartSegmentLevel: 3100,
            /** The current exclusive segment ends (e.g., level complete/exit). */
            EndSegmentLevel: 3101,
            /** Exclusive segment exits without completion. */
            AbandonSegmentLevel: 3102,
            /** Exclusive segment resumes/restores. */
            ResumeSegmentLevel: 3103,
            /** A subsegment within the exclusive segment begins (e.g., round start). */
            StartSubsegmentRound: 3110,
            /** A subsegment within the exclusive segment ends. */
            EndSubsegmentRound: 3111,
            /** Subsegment exits without completion. */
            AbandonSubsegmentRound: 3112,
            /** Subsegment resumes/restores. */
            ResumeSubsegmentRound: 3113,
        }),
        NonExclusiveSegments: Object.freeze({
            /** A non-exclusive segment begins. */
            StartSegmentQuestObjective: 3200,
            /** A non-exclusive segment ends/completes. */
            EndSegmentQuestObjective: 3201,
            /** A non-exclusive segment is abandoned. */
            AbandonSegmentQuestObjective: 3202,
            /** A non-exclusive segment resumes/restores. */
            ResumeSegmentQuestObjective: 3203,
        }),
        SpatialRegions: Object.freeze({
            /** Player enters a spatial region/area. */
            EnterRegion: 3300,
            /** Player exits a spatial region/area. */
            ExitRegion: 3301,
            /** Region is exited via interruption/quit (without normal exit). */
            AbandonRegion: 3302,
            /** Player returns to a region via restore/resume. */
            ResumeRegion: 3303,
        }),
    }),
    PlayerAction: Object.freeze({
        UniversalPlayerActions: Object.freeze({
            /** The player submits or commits a response or action. */
            SubmitResponse: 4000,
            /** The player cancels or withdraws a previously initiated response. */
            CancelSubmission: 4001,
        }),
        PuzzleConstructedResponse: Object.freeze({
            /** The player picks up or grabs an object. */
            PickUpObject: 4100,
            /** The player places an object in a valid location/configuration. */
            PlaceObjectValid: 4101,
            /** The player attempts to place an object in an invalid location/configuration. */
            PlaceObjectInvalid: 4102,
            /** The player removes an object from its current placement. */
            RemoveObject: 4103,
            /** The player begins rotating an object. */
            StartRotateObject: 4104,
            /** The player finishes rotating an object. */
            EndRotateObject: 4105,
            /** The player previews a potential object placement. */
            PreviewPlacement: 4106,
            /** The player modifies an object’s state or configuration. */
            ModifyObject: 4107,
        }),
        PointAndClick: Object.freeze({
            /** The player selects an object. */
            SelectObject: 4200,
            /** The player deselects an object. */
            DeselectObject: 4201,
            /** The player activates or triggers an object. */
            ActivateObject: 4202,
            /** The player changes an object’s state through interaction. */
            ChangeObjectState: 4203,
            /** The player inspects or examines an object. */
            InspectObject: 4204,
            /** The player applies or uses an object. */
            UseObject: 4205,
            /** The player begins panning the view. */
            StartPanView: 4206,
            /** The player ends panning the view. */
            EndPanView: 4207,
        }),
        Combat: Object.freeze({
            /** The player selects a combat target. */
            SelectTarget: 4300,
            /** The player initiates an attack. */
            InitiateAttack: 4301,
            /** The player performs a defensive action. */
            Defend: 4302,
            /** The player attempts to evade an attack. */
            Evade: 4303,
            /** The player uses a combat ability. */
            UseAbility: 4304,
            /** The player begins aiming. */
            StartAim: 4305,
            /** The player finishes aiming. */
            EndAim: 4306,
        }),
        Navigation: Object.freeze({
            /** The player begins moving. */
            StartMovement: 4400,
            /** The player stops moving. */
            EndMovement: 4401,
            /** The player enters a defined area. */
            EnterArea: 4402,
            /** The player exits a defined area. */
            ExitArea: 4403,
            /** The player sets a movement destination. */
            SetDestination: 4404,
            /** The player snaps to a specific location. */
            SnapToLocation: 4405,
            /** The player advances time. */
            AdvanceTime: 4406,
        }),
        ResourceManagement: Object.freeze({
            /** The player purchases a resource or item. */
            Buy: 4500,
            /** The player sells a resource or item. */
            Sell: 4501,
            /** The player stores a resource or item. */
            Store: 4502,
            /** The player collects or acquires a resource. */
            Collect: 4503,
            /** The player uses or consumes a resource. */
            UseResource: 4504,
            /** The player loses a resource. */
            LoseResource: 4505,
            /** The player discards a resource. */
            DiscardResource: 4506,
            /** The player allocates a resource. */
            AllocateResource: 4507,
            /** The player converts one resource into another. */
            ConvertResource: 4508,
        }),
        Simulation: Object.freeze({
            /** The player assigns an entity or resource. */
            Assign: 4600,
            /** The player removes an assignment. */
            Unassign: 4601,
            /** The player sets a priority value. */
            SetPriority: 4602,
            /** The player adjusts a simulation parameter. */
            AdjustParameter: 4603,
            /** The player schedules a simulation action. */
            ScheduleAction: 4604,
            /** The player pauses the simulation. */
            PauseSimulation: 4605,
            /** The player resumes the simulation. */
            ResumeSimulation: 4606,
            /** The player requests the current simulation state. */
            RequestCurrentState: 4607,
        }),
        InterfaceStructuralNavigation: Object.freeze({
            /** The player selects a segment or subsegment. */
            SelectSegment: 4700,
            /** The player opens an in-game interface element. */
            OpenInterface: 4701,
            /** The player closes an in-game interface element. */
            CloseInterface: 4702,
            /** The player navigates to a different in-game screen. */
            NavigateToScreen: 4703,
            /** The player returns to the previous in-game screen. */
            ReturnToPreviousScreen: 4704,
            /** The player selects an interface item. */
            SelectItem: 4705,
            /** The player confirms a selection. */
            ConfirmSelection: 4706,
            /** The player cancels a selection. */
            CancelSelection: 4707,
            /** The player switches views. */
            SwitchView: 4708,
            /** The player toggles an overlay. */
            ToggleOverlay: 4709,
        }),
    }),
    OtherHumanPlayerAction: Object.freeze({
        PuzzleConstructedResponse: Object.freeze({
            /** Mirrors 4100: The player picks up or grabs an object. */
            PickUpObject: 5100,
            /** Mirrors 4101: The player places an object in a valid location/configuration. */
            PlaceObjectValid: 5101,
            /** Mirrors 4102: The player attempts to place an object in an invalid location/configuration. */
            PlaceObjectInvalid: 5102,
            /** Mirrors 4103: The player removes an object from its current placement. */
            RemoveObject: 5103,
            /** Mirrors 4104: The player begins rotating an object. */
            StartRotateObject: 5104,
            /** Mirrors 4105: The player finishes rotating an object. */
            EndRotateObject: 5105,
            /** Mirrors 4106: The player previews a potential object placement. */
            PreviewPlacement: 5106,
            /** Mirrors 4107: The player modifies an object’s state or configuration. */
            ModifyObject: 5107,
        }),
        PointAndClick: Object.freeze({
            /** Mirrors 4200: The player selects an object. */
            SelectObject: 5200,
            /** Mirrors 4201: The player deselects an object. */
            DeselectObject: 5201,
            /** Mirrors 4202: The player activates or triggers an object. */
            ActivateObject: 5202,
            /** Mirrors 4203: The player changes an object’s state through interaction. */
            ChangeObjectState: 5203,
            /** Mirrors 4204: The player inspects or examines an object. */
            InspectObject: 5204,
            /** Mirrors 4205: The player applies or uses an object. */
            UseObject: 5205,
            /** Mirrors 4206: The player begins panning the view. */
            StartPanView: 5206,
            /** Mirrors 4207: The player ends panning the view. */
            EndPanView: 5207,
        }),
        Combat: Object.freeze({
            /** Mirrors 4300: The player selects a combat target. */
            SelectTarget: 5300,
            /** Mirrors 4301: The player initiates an attack. */
            InitiateAttack: 5301,
            /** Mirrors 4302: The player performs a defensive action. */
            Defend: 5302,
            /** Mirrors 4303: The player attempts to evade an attack. */
            Evade: 5303,
            /** Mirrors 4304: The player uses a combat ability. */
            UseAbility: 5304,
            /** Mirrors 4305: The player begins aiming. */
            StartAim: 5305,
            /** Mirrors 4306: The player finishes aiming. */
            EndAim: 5306,
        }),
        Navigation: Object.freeze({
            /** Mirrors 4400: The player begins moving. */
            StartMovement: 5400,
            /** Mirrors 4401: The player stops moving. */
            EndMovement: 5401,
            /** Mirrors 4402: The player enters a defined area. */
            EnterArea: 5402,
            /** Mirrors 4403: The player exits a defined area. */
            ExitArea: 5403,
            /** Mirrors 4404: The player sets a movement destination. */
            SetDestination: 5404,
            /** Mirrors 4405: The player snaps to a specific location. */
            SnapToLocation: 5405,
            /** Mirrors 4406: The player advances time. */
            AdvanceTime: 5406,
        }),
        ResourceManagement: Object.freeze({
            /** Mirrors 4500: The player purchases a resource or item. */
            Buy: 5500,
            /** Mirrors 4501: The player sells a resource or item. */
            Sell: 5501,
            /** Mirrors 4502: The player stores a resource or item. */
            Store: 5502,
            /** Mirrors 4503: The player collects or acquires a resource. */
            Collect: 5503,
            /** Mirrors 4504: The player uses or consumes a resource. */
            UseResource: 5504,
            /** Mirrors 4505: The player loses a resource. */
            LoseResource: 5505,
            /** Mirrors 4506: The player discards a resource. */
            DiscardResource: 5506,
            /** Mirrors 4507: The player allocates a resource. */
            AllocateResource: 5507,
            /** Mirrors 4508: The player converts one resource into another. */
            ConvertResource: 5508,
        }),
        Simulation: Object.freeze({
            /** Mirrors 4600: The player assigns an entity or resource. */
            Assign: 5600,
            /** Mirrors 4601: The player removes an assignment. */
            Unassign: 5601,
            /** Mirrors 4602: The player sets a priority value. */
            SetPriority: 5602,
            /** Mirrors 4603: The player adjusts a simulation parameter. */
            AdjustParameter: 5603,
            /** Mirrors 4604: The player schedules a simulation action. */
            ScheduleAction: 5604,
            /** Mirrors 4605: The player pauses the simulation. */
            PauseSimulation: 5605,
            /** Mirrors 4606: The player resumes the simulation. */
            ResumeSimulation: 5606,
            /** Mirrors 4607: The player requests the current simulation state. */
            RequestCurrentState: 5607,
        }),
        InterfaceStructuralNavigation: Object.freeze({
            /** Mirrors 4700: The player selects a segment or subsegment. */
            SelectSegment: 5700,
            /** Mirrors 4701: The player opens an in-game interface element. */
            OpenInterface: 5701,
            /** Mirrors 4702: The player closes an in-game interface element. */
            CloseInterface: 5702,
            /** Mirrors 4703: The player navigates to a different in-game screen. */
            NavigateToScreen: 5703,
            /** Mirrors 4704: The player returns to the previous in-game screen. */
            ReturnToPreviousScreen: 5704,
            /** Mirrors 4705: The player selects an interface item. */
            SelectItem: 5705,
            /** Mirrors 4706: The player confirms a selection. */
            ConfirmSelection: 5706,
            /** Mirrors 4707: The player cancels a selection. */
            CancelSelection: 5707,
            /** Mirrors 4708: The player switches views. */
            SwitchView: 5708,
            /** Mirrors 4709: The player toggles an overlay. */
            ToggleOverlay: 5709,
        }),
    }),
    SystemControlledActorAction: Object.freeze({
        PuzzleConstructedResponse: Object.freeze({
            /** Mirrors 4100: The player picks up or grabs an object. */
            PickUpObject: 6100,
            /** Mirrors 4101: The player places an object in a valid location/configuration. */
            PlaceObjectValid: 6101,
            /** Mirrors 4102: The player attempts to place an object in an invalid location/configuration. */
            PlaceObjectInvalid: 6102,
            /** Mirrors 4103: The player removes an object from its current placement. */
            RemoveObject: 6103,
            /** Mirrors 4104: The player begins rotating an object. */
            StartRotateObject: 6104,
            /** Mirrors 4105: The player finishes rotating an object. */
            EndRotateObject: 6105,
            /** Mirrors 4106: The player previews a potential object placement. */
            PreviewPlacement: 6106,
            /** Mirrors 4107: The player modifies an object’s state or configuration. */
            ModifyObject: 6107,
        }),
        PointAndClick: Object.freeze({
            /** Mirrors 4200: The player selects an object. */
            SelectObject: 6200,
            /** Mirrors 4201: The player deselects an object. */
            DeselectObject: 6201,
            /** Mirrors 4202: The player activates or triggers an object. */
            ActivateObject: 6202,
            /** Mirrors 4203: The player changes an object’s state through interaction. */
            ChangeObjectState: 6203,
            /** Mirrors 4204: The player inspects or examines an object. */
            InspectObject: 6204,
            /** Mirrors 4205: The player applies or uses an object. */
            UseObject: 6205,
            /** Mirrors 4206: The player begins panning the view. */
            StartPanView: 6206,
            /** Mirrors 4207: The player ends panning the view. */
            EndPanView: 6207,
        }),
        Combat: Object.freeze({
            /** Mirrors 4300: The player selects a combat target. */
            SelectTarget: 6300,
            /** Mirrors 4301: The player initiates an attack. */
            InitiateAttack: 6301,
            /** Mirrors 4302: The player performs a defensive action. */
            Defend: 6302,
            /** Mirrors 4303: The player attempts to evade an attack. */
            Evade: 6303,
            /** Mirrors 4304: The player uses a combat ability. */
            UseAbility: 6304,
            /** Mirrors 4305: The player begins aiming. */
            StartAim: 6305,
            /** Mirrors 4306: The player finishes aiming. */
            EndAim: 6306,
        }),
        Navigation: Object.freeze({
            /** Mirrors 4400: The player begins moving. */
            StartMovement: 6400,
            /** Mirrors 4401: The player stops moving. */
            EndMovement: 6401,
            /** Mirrors 4402: The player enters a defined area. */
            EnterArea: 6402,
            /** Mirrors 4403: The player exits a defined area. */
            ExitArea: 6403,
            /** Mirrors 4404: The player sets a movement destination. */
            SetDestination: 6404,
            /** Mirrors 4405: The player snaps to a specific location. */
            SnapToLocation: 6405,
            /** Mirrors 4406: The player advances time. */
            AdvanceTime: 6406,
        }),
        ResourceManagement: Object.freeze({
            /** Mirrors 4500: The player purchases a resource or item. */
            Buy: 6500,
            /** Mirrors 4501: The player sells a resource or item. */
            Sell: 6501,
            /** Mirrors 4502: The player stores a resource or item. */
            Store: 6502,
            /** Mirrors 4503: The player collects or acquires a resource. */
            Collect: 6503,
            /** Mirrors 4504: The player uses or consumes a resource. */
            UseResource: 6504,
            /** Mirrors 4505: The player loses a resource. */
            LoseResource: 6505,
            /** Mirrors 4506: The player discards a resource. */
            DiscardResource: 6506,
            /** Mirrors 4507: The player allocates a resource. */
            AllocateResource: 6507,
            /** Mirrors 4508: The player converts one resource into another. */
            ConvertResource: 6508,
        }),
        Simulation: Object.freeze({
            /** Mirrors 4600: The player assigns an entity or resource. */
            Assign: 6600,
            /** Mirrors 4601: The player removes an assignment. */
            Unassign: 6601,
            /** Mirrors 4602: The player sets a priority value. */
            SetPriority: 6602,
            /** Mirrors 4603: The player adjusts a simulation parameter. */
            AdjustParameter: 6603,
            /** Mirrors 4604: The player schedules a simulation action. */
            ScheduleAction: 6604,
            /** Mirrors 4605: The player pauses the simulation. */
            PauseSimulation: 6605,
            /** Mirrors 4606: The player resumes the simulation. */
            ResumeSimulation: 6606,
            /** Mirrors 4607: The player requests the current simulation state. */
            RequestCurrentState: 6607,
        }),
        InterfaceStructuralNavigation: Object.freeze({
            /** Mirrors 4700: The player selects a segment or subsegment. */
            SelectSegment: 6700,
            /** Mirrors 4701: The player opens an in-game interface element. */
            OpenInterface: 6701,
            /** Mirrors 4702: The player closes an in-game interface element. */
            CloseInterface: 6702,
            /** Mirrors 4703: The player navigates to a different in-game screen. */
            NavigateToScreen: 6703,
            /** Mirrors 4704: The player returns to the previous in-game screen. */
            ReturnToPreviousScreen: 6704,
            /** Mirrors 4705: The player selects an interface item. */
            SelectItem: 6705,
            /** Mirrors 4706: The player confirms a selection. */
            ConfirmSelection: 6706,
            /** Mirrors 4707: The player cancels a selection. */
            CancelSelection: 6707,
            /** Mirrors 4708: The player switches views. */
            SwitchView: 6708,
            /** Mirrors 4709: The player toggles an overlay. */
            ToggleOverlay: 6709,
        }),
    }),
    SystemAction: Object.freeze({
        EntityResourceChanges: Object.freeze({
            /** The system introduces a new entity into active gameplay. */
            CreateEntity: 7110,
            /** The system removes an entity from active gameplay. */
            RemoveEntity: 7111,
            /** The system changes an entity’s form, type, or role while preserving continuity within gameplay. */
            TransformEntity: 7112,
            /** The system increases the value of a gameplay resource. */
            IncrementResource: 7120,
            /** The system decreases the value of a gameplay resource. */
            DecrementResource: 7121,
            /** The system advances or updates a counter or timer variable. */
            UpdateCounter: 7122,
        }),
        MovementSpatialChange: Object.freeze({
            /** The system initiates continuous movement of an entity. */
            StartEntityMovement: 7200,
            /** The system ends continuous movement of an entity. */
            EndEntityMovement: 7201,
            /** The system instantly relocates an entity to a new position. */
            RepositionEntity: 7202,
            /** The system initiates movement of an environmental gameplay element. */
            StartEnvironmentMovement: 7203,
            /** The system ends movement of an environmental gameplay element. */
            EndEnvironmentMovement: 7204,
            /** The system instantly relocates an environmental gameplay element. */
            RepositionEnvironmentElement: 7205,
        }),
        SimulationExecution: Object.freeze({
            /** The system initializes a simulation process. */
            InitializeSimulation: 7300,
            /** The system begins executing a simulation. */
            StartSimulation: 7301,
            /** The system pauses simulation execution. */
            PauseSimulation: 7302,
            /** The system resumes a paused simulation. */
            ResumeSimulation: 7303,
            /** The system advances the simulation by a discrete step or interval. */
            AdvanceSimulation: 7304,
            /** The system resets the simulation to a baseline state. */
            ResetSimulation: 7305,
            /** The system terminates simulation execution. */
            TerminateSimulation: 7306,
        }),
        InformationVisibility: Object.freeze({
            /** The system makes gameplay-relevant information visible or discoverable to the player. */
            RevealInformation: 7400,
            /** The system hides gameplay-relevant information from the player. */
            ConcealInformation: 7401,
        }),
        InGameInterfaceState: Object.freeze({
            /** The system displays an in-game interface element. */
            DisplayInterfaceElement: 7500,
            /** The system hides an in-game interface element. */
            HideInterfaceElement: 7501,
            /** The system updates the content or state of an interface element. */
            UpdateInterfaceElement: 7502,
            /** The system enables interaction with an interface element. */
            EnableInterfaceElement: 7503,
            /** The system disables interaction with an interface element. */
            DisableInterfaceElement: 7504,
        }),
        SystemSignaling: Object.freeze({
            /** The system begins emitting a gameplay-relevant audiovisual signal. */
            StartSystemSignal: 7600,
            /** The system stops emitting a gameplay-relevant audiovisual signal. */
            EndSystemSignal: 7601,
            /** The system changes the type or state of an active signal. */
            ChangeSystemSignal: 7602,
        }),
    }),
});
